apiVersion: v1
kind: Secret
metadata:
  name: azure-postgres-secret-prod
type: Opaque
stringData:
  DB_USER: $(DB_USER)
  DB_PASSWORD: $(DB_PASSWORD)
  DB_URL: $(DB_URL)

  MAIL_USERNAME: $(MAIL_USERNAME)
  MAIL_PASSWORD: $(MAIL_PASSWORD)

  JWT_SECRET_KEY: $(JWT_SECRET_KEY)

#  DB-USER: "bankadmin"
#  DB-PASSWORD: "Azure@123"
#  DB-URL: "jdbc:postgresql://bankdbserver.postgres.database.azure.com:5432/postgres?user=bankadmin&password=Azure@123&sslmode=require"
#  MAIL-USERNAME: "monicaglory05@gmail.com"
#  MAIL-PASSWORD: "glrl jnwj twwo deza"
#  JWT-SECRET-KEY: "notsosupersecretkeybgjhrebgjreborebjrebvjkfnbjbtjnbtjnbktjnbjtnbjt"
#



