apiVersion: v1
kind: Service
metadata:
  name: springboot-backend-service-prod
  labels:
    app: springboot-backend
    env: prod
spec:
  type: LoadBalancer
  loadBalancerIP: 4.224.75.153
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: springboot-backend
    env: prod
